spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flowable-spring-boot?characterEncoding=UTF-8
    username: flowable
    password: flowable
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
