{{- if .Values.portal_gateway.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "gateway.name" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  {{- with .Values.portal_gateway.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.portal_gateway.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.global.gateway.domain_head }}{{ .Values.global.domain}}
        secretName: {{ .Values.portal_gateway.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.global.gateway.domain_head }}{{ .Values.global.domain}}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "gateway.name" . }}
              servicePort: 80
{{- end }}
