apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.portal_gateway.server.name | quote }}
  labels:
{{ include "gateway.labels" . | indent 4 }}
    app.name: {{ .Values.portal_gateway.server.name | quote }}
spec:
  type: {{ .Values.portal_gateway.server.service.type }}
  ports:
    - name: {{ .Values.portal_gateway.server.name | quote }}
      port: 80
      targetPort: {{ .Values.portal_gateway.server.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.name: {{ .Values.portal_gateway.server.name | quote }}
